# Generated from proto/v1/training_api.proto. DO NOT EDIT.
# Generated by protoc-gen-grpc-py v0.2.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import TYPE_CHECKING

from grpc import StatusCode, method_handlers_generic_handler, unary_unary_rpc_method_handler

from .training_api_pb import TrainRequest, TrainResponse

if TYPE_CHECKING:
    from collections.abc import Sequence

    from grpc import CallCredentials, Channel, Compression, Server, ServicerContext, aio


class TrainingAPIServiceService:
    async def train(self, request: TrainRequest, context: aio.ServicerContext) -> TrainResponse:
        context.set_code(StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def add_to_server(self, server: aio.Server) -> None:
        """Register this service's RPC handlers with a grpc server."""
        rpc_method_handlers = {
            "Train": unary_unary_rpc_method_handler(
                self.train,
                request_deserializer=TrainRequest.from_binary,
                response_serializer=TrainResponse.to_binary,
            ),
        }
        generic_handler = method_handlers_generic_handler(
            "proto.v1.TrainingAPIService",
            rpc_method_handlers,
        )
        server.add_generic_rpc_handlers((generic_handler,))


class TrainingAPIServiceClient:
    def __init__(self, channel: aio.Channel) -> None:
        self._train = channel.unary_unary(
            "/proto.v1.TrainingAPIService/Train",
            request_serializer=TrainRequest.to_binary,
            response_deserializer=TrainResponse.from_binary,
        )

    def train(
        self,
        request: TrainRequest,
        *,
        timeout: float | None = None,
        metadata: aio.Metadata | Sequence[tuple[str, str | bytes]] | None = None,
        credentials: CallCredentials | None = None,
        wait_for_ready: bool | None = None,
        compression: Compression | None = None,
    ) -> aio.UnaryUnaryCall[TrainRequest, TrainResponse]:
        return self._train(request, timeout=timeout, metadata=metadata, credentials=credentials, wait_for_ready=wait_for_ready, compression=compression)


class TrainingAPIServiceServiceSync:
    def train(self, request: TrainRequest, context: ServicerContext) -> TrainResponse:
        context.set_code(StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def add_to_server(self, server: Server) -> None:
        """Register this service's RPC handlers with a grpc server."""
        rpc_method_handlers = {
            "Train": unary_unary_rpc_method_handler(
                self.train,
                request_deserializer=TrainRequest.from_binary,
                response_serializer=TrainResponse.to_binary,
            ),
        }
        generic_handler = method_handlers_generic_handler(
            "proto.v1.TrainingAPIService",
            rpc_method_handlers,
        )
        server.add_generic_rpc_handlers((generic_handler,))


class TrainingAPIServiceClientSync:
    def __init__(self, channel: Channel) -> None:
        self._train = channel.unary_unary(
            "/proto.v1.TrainingAPIService/Train",
            request_serializer=TrainRequest.to_binary,
            response_deserializer=TrainResponse.from_binary,
        )

    def train(
        self,
        request: TrainRequest,
        *,
        timeout: float | None = None,
        metadata: tuple[tuple[str, str | bytes], ...] | None = None,
        credentials: CallCredentials | None = None,
        wait_for_ready: bool | None = None,
        compression: Compression | None = None,
    ) -> TrainResponse:
        return self._train(request, timeout=timeout, metadata=metadata, credentials=credentials, wait_for_ready=wait_for_ready, compression=compression)
