# Generated from proto/v1/training_api.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.2.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

if TYPE_CHECKING:
    from protobuf import DescFile


_TrainRequestFields: TypeAlias = Literal["model_id", "peft_id"]

class TrainRequest(Message[_TrainRequestFields]):
    """
    ```proto
    message proto.v1.TrainRequest
    ```

    Attributes:
        model_id:
            ```proto
            string model_id = 1;
            ```
        peft_id:
            ```proto
            string peft_id = 2;
            ```
    """

    __slots__ = ("model_id", "peft_id")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            model_id: str = "",
            peft_id: str = "",
        ) -> None:
            pass

        model_id: str
        peft_id: str

_TrainResponseFields: TypeAlias = Literal["job_id"]

class TrainResponse(Message[_TrainResponseFields]):
    """
    ```proto
    message proto.v1.TrainResponse
    ```

    Attributes:
        job_id:
            ```proto
            string job_id = 1;
            ```
    """

    __slots__ = ("job_id",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            job_id: str = "",
        ) -> None:
            pass

        job_id: str


_DESC = file_desc(
    b'\n\x1bproto/v1/training_api.proto\x12\x08proto.v1"B\n\x0cTrainRequest\x12\x19\n\x08model_id\x18\x01 \x01(\tR\x07modelId\x12\x17\n\x07peft_id\x18\x02 \x01(\tR\x06peftId"&\n\rTrainResponse\x12\x15\n\x06job_id\x18\x01 \x01(\tR\x05jobId2P\n\x12TrainingAPIService\x12:\n\x05Train\x12\x16.proto.v1.TrainRequest\x1a\x17.proto.v1.TrainResponse"\x00b\x06proto3',
    [],
    {
        "TrainRequest": TrainRequest,
        "TrainResponse": TrainResponse,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `proto/v1/training_api.proto`."""
    return _DESC
